services:
  es:
    image: elasticsearch:8.17.0
    ports:
      - 9200:9200
      - 9300:9300
    mem_limit: 1g

    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - 'ES_JAVA_OPTS=-XX:UseSVE=0'
      - 'CLI_JAVA_OPTS=-XX:UseSVE=0'
      - ELASTIC_PASSWORD=test
      - xpack.security.enabled=false

  kibana:
    image: kibana:8.17.0
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://es:9200
    depends_on:
      - es

  beats:
    image: elastic/filebeat:8.17.0
    volumes:
      - ./beats/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./beats/log:/var/log/work
    environment:
      - ELASTICSEARCH_URL=http://172.19.0.2:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=test
    command: ["--strict.perms=false"]
